name: Timesketch Docker Build & Push

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: main
        
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1.2.0
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1.6.0    
      
    - name: Login to Github Package Repo
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: epod
        password: ${{ secrets.EPOD_PACKAGES_PAT }}
        
    -  name: Build and Push to Docker Package Repo
       id: docker_build
       uses: mr-smithers-excellent/docker-build-push@v5.6
       with:
         image: timesketch
         registry: ghcr.io
         githubOrg: epod
         tags: latest  
